# Generated by Django 4.0.4 on 2022-04-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectedrelated', '0002_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
    ]
