# Generated by Django 4.0.4 on 2022-05-12 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selectedrelated', '0004_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_name', to='selectedrelated.author'),
        ),
    ]
