# Generated by Django 4.0.4 on 2022-05-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectedrelated', '0005_alter_books_author'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='students',
            managers=[
            ],
        ),
    ]
